In [1]:
import torch


In [2]:
a = torch.tensor([[1,3,5],[2,6,8]])
print(a.sum(axis=0),a.sum(axis=1))

tensor([ 3,  9, 13]) tensor([ 9, 16])


In [6]:
a_sum = a.sum(axis=1,keepdim=True)
print(a_sum,a_sum.shape)

tensor([[ 9],
        [16]]) torch.Size([2, 1]) tensor([9])


In [19]:
b = torch.arange(3)
y = torch.ones(3, dtype=torch.long)
b,y,torch.dot(b,y)

(tensor([0, 1, 2]), tensor([1, 1, 1]), tensor(3))

In [31]:
a = torch.arange(6).reshape(2,3)
b = torch.torch.tensor([1,3,5])
c = torch.tensor([[1,3],[2,6],[5,8]])
a,b,c,torch.mv(a,b),torch.mm(a,c)   #matrix-vector multiplication, matix-matrix multiplication

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([1, 3, 5]),
 tensor([[1, 3],
         [2, 6],
         [5, 8]]),
 tensor([13, 40]),
 tensor([[12, 22],
         [36, 73]]))

In [30]:
x = torch.tensor([3,-4], dtype=torch.float32)
torch.norm(x), torch.abs(x)    # l2 norm(sum(x^2)), abs(x)

(tensor(5.), tensor([3., 4.]))